# fly.toml app configuration file generated for display-geodata-api on 2023-06-06T17:19:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "display-geodata-api"
primary_region = "cdg"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "display-geodata-api.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
